### ISSUE TITLE
Error: Failed request: (401) on publish extension

### ISSUE THREAD

**Issue by dannysteenman** [HaaLeo/publish-vscode-extension#21]
I'm getting the following error when I try to publish my extension to VSCE:

```
Run HaaLeo/publish-vscode-extension@v1
[2](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:2)
  with:
[3](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:3)
    pat: ***
[4](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:4)
    registryUrl: https://marketplace.visualstudio.com/
[5](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:5)
    packagePath: ./
[6](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:6)
    yarn: false
[7](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:7)
    dryRun: false
[8](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:8)
    noVerify: false
[9](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:9)
    preRelease: false
[10](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:10)
  env:
[11](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:11)
    pythonLocation: /opt/hostedtoolcache/Python/3.10.4/x64
[12](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:12)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.4/x64/lib
[13](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:13)
Specifically, running GitHub Action HaaLeo/publish-vscode-extension@v1.0.2.
[14](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:14)
Package the Extension
[15](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:15)
  Start packaging the extension.
[16](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:16)
   DONE  Packaged: cloudformation-yaml-snippets-3.58.0.vsix (19 files, 9.39MB)
[17](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:17)

[18](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:18)
Publish the Extension
[19](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:19)
  (node:2560) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[20](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:20)
  (Use `node --trace-deprecation ...` to show where the warning was created)
[21](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:21)
   INFO  Publishing 'dannysteenman.cloudformation-yaml-snippets v3.58.0'...
[22](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:22)
Error: Error: Failed request: (401)
[23](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:23)
    at RestClient.<anonymous> (/home/runner/work/_actions/HaaLeo/publish-vscode-extension/v1/dist/index.js:101043:31)
[24](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:24)
    at Generator.next (<anonymous>)
[25](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:25)
    at fulfilled (/home/runner/work/_actions/HaaLeo/publish-vscode-extension/v1/dist/index.js:100847:58)
[26](https://github.com/dannysteenman/vscode-cloudformation-snippets/runs/6128051575?check_suite_focus=true#step:8:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
This is the how I configured the step in my github workflow:

```
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToVSCE
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
```

**Comment by dannysteenman** [comment]
My bad... I switched publisher id's and therefore needed a new personal access token, hence the error.
